CREATE TABLE IF NOT EXISTS tb_categorias (
    id_cat INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    nombre_cat VARCHAR(100) NOT NULL,
    desc_cat VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS rol (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nombre VARCHAR(255) NOT NULL UNIQUE
);
